repos:
  # isort should run before black as black sometimes tweaks the isort output
  - repo: https://github.com/PyCQA/isort
    rev: 5.5.3
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args: ["--ignore=E203,E711,W503"]

  - repo: https://github.com/PyCQA/doc8
    rev: 0.8.1rc2
    hooks:
      - id: doc8
        args: ["--max-line-length", "100", "--allow-long-titles"]
